name: tuket_app
description: "Tuket App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # UI ve Gelişmiş Bileşenler
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0

  # Durum Yönetimi
  provider: ^6.1.2

  # Ağ İstekleri (API Bağlantısı)
  dio: ^5.4.3+1
  http: ^1.2.1

  # JSON İşleme
  json_serializable: ^6.8.0

  # Yerel Depolama
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Kullanıcı Kimlik Doğrulama (JWT)
  flutter_secure_storage: ^9.2.2

  # Form Doğrulama
  email_validator: ^2.1.17
  flutter_form_builder: ^9.2.1

  # Haritalar ve Konum Servisleri
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # QR Kod Okuyucu
  qr_flutter: ^4.1.0

  # WebView
  webview_flutter: ^4.7.0

  # Durum Yönetimi - State Management (Opsiyonel)
  riverpod: ^2.4.9

  # Animasyonlar
  animations: ^2.0.11

  # Günlükleme ve Hata Raporlama
  logger: ^2.3.0
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900